export const AppPermissions = {
  // Overview
  OVERVIEW_VIEW: 'OVERVIEW_VIEW',
  SHOW_OVERVIEW_MISSED_REPOSSESSIONS: 'SHOW_OVERVIEW_MISSED_REPOSSESSIONS',
  SHOW_OVERVIEW_TOTAL_ASSIGNMENTS: 'SHOW_OVERVIEW_TOTAL_ASSIGNMENTS',
  SHOW_OVERVIEW_TOTAL_REPOSSESSIONS: 'SHOW_OVERVIEW_TOTAL_REPOSSESSIONS',
  SHOW_OVERVIEW_TOTAL_RECOVERY_RATE: 'SHOW_OVERVIEW_TOTAL_RECOVERY_RATE',
  SHOW_OVERVIEW_TOP_CAMERA_CARS: 'SHOW_OVERVIEW_TOP_CAMERA_CARS',
  SHOW_OVERVIEW_TOP_RECOVERY_AGENTS: 'SHOW_OVERVIEW_TOP_RECOVERY_AGENTS',
  SHOW_OVERVIEW_TOP_SPOTTERS: 'SHOW_OVERVIEW_TOP_SPOTTERS',

  // Reports
  REPORTS_VIEW: 'REPORTS_VIEW',

  // Active shifts
  ACTIVE_SHIFTS_VIEW: 'ACTIVE_SHIFTS_VIEW',

  // Active shifts V2
  ACTIVE_SHIFTS_V2_VIEW: 'ACTIVE_SHIFTS_V2_VIEW',

  // Shift management
  SHIFT_MANAGEMENT_VIEW: 'SHIFT_MANAGEMENT_VIEW',

  // My Stats
  MY_STATS_VIEW: 'MY_STATS_VIEW',

  // Dashboard
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',

  // Users
  USERS_VIEW: 'USERS_VIEW',
  SHOW_USERS_METRIC_CHART: 'SHOW_USERS_METRIC_CHART',

  // User Detail
  USER_DETAIL_VIEW: 'USER_DETAIL_VIEW',
  SHOW_USER_DETAIL_CHECKLIST: 'SHOW_USER_DETAIL_CHECKLIST',
  SHOW_USER_DETAil_INFRACTION_HISTORY_TAB: 'SHOW_USER_DETAil_INFRACTION_HISTORY_TAB',
  SHOW_USER_DETAil_COMMISSION_HISTORY_TAB: 'SHOW_USER_DETAil_COMMISSION_HISTORY_TAB',
  SHOW_USER_DETAil_TASK_HISTORY_TAB: 'SHOW_USER_DETAil_TASK_HISTORY_TAB',
  SHOW_USER_DETAil_ACTIVITY_HISTORY_TAB: 'SHOW_USER_DETAil_ACTIVITY_HISTORY_TAB',

  // Tasks
  TASKS_VIEW: 'TASKS_VIEW',

  // Commissions
  COMMISSIONS_VIEW: 'COMMISSIONS_VIEW',

  // Checklist
  CHECKLIST_VIEW: 'CHECKLIST_VIEW',

  // User Activity
  USER_ACTIVITY_VIEW: 'USER_ACTIVITY_VIEW',

  // Time Sheet
  TIME_SHEET_VIEW: 'TIME_SHEET_VIEW',

  // Time Sheet
  TIME_SHEET_PAT_VIEW: 'TIME_SHEET_PAT_VIEW',

  // Edit Company
  EDIT_COMPANY_VIEW: 'EDIT_COMPANY_VIEW',

  // Notifications
  NOTIFICATIONS_VIEW: 'NOTIFICATIONS_VIEW',

  // Settings
  SETTINGS_VIEW: 'SETTINGS_VIEW',

  // Subscription Management
  SUBSCRIPTION_MANAGEMENT_VIEW: 'SUBSCRIPTION_MANAGEMENT_VIEW',

  // Top Nav
  SHOW_TOPNAV_START_SHIFT_BUTTON: 'SHOW_TOPNAV_START_SHIFT_BUTTON',

  // Super Admin
  SUPER_ADMIN_VIEW: 'SUPER_ADMIN_VIEW',
};
