export const Permissions = {
  // Overview
  SHOW_TOTAL_ASSIGNMENTS: 'SHOW_TOTAL_ASSIGNMENTS',
  SHOW_MISSED_REPOSSESSIONS: 'SHOW_MISSED_REPOSSESSIONS',
  SHOW_TOP_CAMERA_CARS: 'SHOW_TOP_CAMERA_CARS',
  SHOW_TOP_RECOVERY_AGENTS: 'SHOW_TOP_RECOVERY_AGENTS',
  SHOW_TOP_SPOTTERS: 'SHOW_TOP_SPOTTERS',
  SHOW_TOTAL_RECOVERY_RATE: 'SHOW_TOTAL_RECOVERY_RATE',
  SHOW_TOTAL_REPOSSESSIONS: 'SHOW_TOTAL_REPOSSESSIONS',

  // Reports

  // Users
  SHOW_DRIVE_TIME_HOURS: 'SHOW_DRIVE_TIME_HOURS',
  SHOW_MISSED_OPPORTUNITIES: 'SHOW_MISSED_OPPORTUNITIES',
  SHOW_NUMBER_OF_INFRACTIONS: 'SHOW_NUMBER_OF_INFRACTIONS',
  SHOW_NUMBER_OF_REPOSSESSIONS: 'SHOW_NUMBER_OF_REPOSSESSIONS',
  SHOW_NUMBER_OF_SPOTTED_VEHICLES: 'SHOW_NUMBER_OF_SPOTTED_VEHICLES',
  SHOW_TASK_STATS: 'SHOW_TASK_STATS',
  SHOW_TOTAL_HOURS_WORKED: 'SHOW_TOTAL_HOURS_WORKED',
  SHOW_TOTAL_COMISSIONS: 'SHOW_TOTAL_COMISSIONS',
};
