export const AppPermissions = {
  // Overview
  OVERVIEW_VIEW: 'OVERVIEW_VIEW',
  SHOW_OVERVIEW_MISSED_REPOSSESSIONS: 'SHOW_OVERVIEW_MISSED_REPOSSESSIONS',
  SHOW_OVERVIEW_TOTAL_ASSIGNMENTS: 'SHOW_OVERVIEW_TOTAL_ASSIGNMENTS',
  SHOW_OVERVIEW_TOTAL_REPOSSESSIONS: 'SHOW_OVERVIEW_TOTAL_REPOSSESSIONS',
  SHOW_OVERVIEW_TOTAL_RECOVERY_RATE: 'SHOW_OVERVIEW_TOTAL_RECOVERY_RATE',
  SHOW_OVERVIEW_TOP_CAMERA_CARS: 'SHOW_OVERVIEW_TOP_CAMERA_CARS',
  SHOW_OVERVIEW_TOP_RECOVERY_AGENTS: 'SHOW_OVERVIEW_TOP_RECOVERY_AGENTS',
  SHOW_OVERVIEW_TOP_SPOTTERS: 'SHOW_OVERVIEW_TOP_SPOTTERS',

  // Reports
  REPORTS_VIEW: 'REPORTS_VIEW',

  // Agent Reports
  AGENT_REPORTS_VIEW: 'AGENT_REPORTS_VIEW',

  // Active shifts
  ACTIVE_SHIFTS_VIEW: 'ACTIVE_SHIFTS_VIEW',

  // Active shifts V2
  ACTIVE_SHIFTS_V2_VIEW: 'ACTIVE_SHIFTS_V2_VIEW',

  // Shift management
  SHIFT_MANAGEMENT_VIEW: 'SHIFT_MANAGEMENT_VIEW',

  // My Stats
  MY_STATS_VIEW: 'MY_STATS_VIEW',

  // Dashboard
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',

  // Users
  USERS_VIEW: 'USERS_VIEW',
  SHOW_USERS_METRIC_CHART: 'SHOW_USERS_METRIC_CHART',

  // User Detail
  USER_DETAIL_VIEW: 'USER_DETAIL_VIEW',
  SHOW_USER_DETAIL_CHECKLIST: 'SHOW_USER_DETAIL_CHECKLIST',
  SHOW_USER_DETAil_INFRACTION_HISTORY_TAB: 'SHOW_USER_DETAil_INFRACTION_HISTORY_TAB',
  SHOW_USER_DETAil_COMMISSION_HISTORY_TAB: 'SHOW_USER_DETAil_COMMISSION_HISTORY_TAB',
  SHOW_USER_DETAil_TASK_HISTORY_TAB: 'SHOW_USER_DETAil_TASK_HISTORY_TAB',
  SHOW_USER_DETAil_ACTIVITY_HISTORY_TAB: 'SHOW_USER_DETAil_ACTIVITY_HISTORY_TAB',

  // Tasks
  TASKS_VIEW: 'TASKS_VIEW',

  // Commissions
  COMMISSIONS_VIEW: 'COMMISSIONS_VIEW',

  // Checklist
  CHECKLIST_VIEW: 'CHECKLIST_VIEW',

  // User Activity
  USER_ACTIVITY_VIEW: 'USER_ACTIVITY_VIEW',

  // Time Sheet
  TIME_SHEET_VIEW: 'TIME_SHEET_VIEW',

  // Time Sheet
  TIME_SHEET_PAT_VIEW: 'TIME_SHEET_PAT_VIEW',

  // Edit Company
  EDIT_COMPANY_VIEW: 'EDIT_COMPANY_VIEW',

  // Notifications
  NOTIFICATIONS_VIEW: 'NOTIFICATIONS_VIEW',

  // Settings
  SETTINGS_VIEW: 'SETTINGS_VIEW',

  // Subscription Management
  SUBSCRIPTION_MANAGEMENT_VIEW: 'SUBSCRIPTION_MANAGEMENT_VIEW',

  // Top Nav
  SHOW_TOPNAV_START_SHIFT_BUTTON: 'SHOW_TOPNAV_START_SHIFT_BUTTON',

  // System View
  SYSTEM_VIEW: 'SYSTEM_VIEW',

  // Super Admin
  SUPER_ADMIN_VIEW: 'SUPER_ADMIN_VIEW',
};


/* User Roles & Types */

export enum UserRoles {
  // System Level
  SYSTEM_ADMIN_ROLE = 'system_admin',
  USER_ROLE = 'user',

  // Company Level
  SUPER_ADMIN_ROLE = 'super_admin',
  ADMIN_ROLE = 'admin',
  MANAGER_ROLE = 'manager',
  DRIVER_ROLE = 'driver',
}

export enum UserTypes {
  SYSTEM_ADMIN_TYPE = 'system_admin',
  SUPER_ADMIN_TYPE = 'super_admin',
  ADMINISTRATOR_TYPE = 'administrator',
  /**
   * @deprecated This is replaced by CUSTOMER_REP.
   */
  ADMIN_REP_TYPE = 'admin_rep',
  CUSTOMER_REP_TYPE = 'customer_rep',
  BRANCH_MANAGER_TYPE = 'branch_manager',
  INVESTIGATOR_TYPE = 'investigator',
  RECOVERY_AGENT_TYPE = 'recovery_agent',
  SPOTTER_TYPE = 'spotter',
  CAMERA_CAR_TYPE = 'camera_car'
}

export const ALL_SYSTEM_ROLES = [
  UserRoles.SYSTEM_ADMIN_ROLE,
  UserRoles.USER_ROLE,
];

export const ALL_COMPANY_ROLES = [
  UserRoles.SUPER_ADMIN_ROLE,
  UserRoles.ADMIN_ROLE,
  UserRoles.MANAGER_ROLE,
  UserRoles.DRIVER_ROLE,
];

export const ALL_USER_TYPES = [
  UserTypes.SYSTEM_ADMIN_TYPE,
  UserTypes.SUPER_ADMIN_TYPE,
  UserTypes.ADMINISTRATOR_TYPE,
  UserTypes.CUSTOMER_REP_TYPE,
  UserTypes.BRANCH_MANAGER_TYPE,
  UserTypes.INVESTIGATOR_TYPE,
  UserTypes.RECOVERY_AGENT_TYPE,
  UserTypes.SPOTTER_TYPE,
  UserTypes.CAMERA_CAR_TYPE,
];

export const ADMIN_ROLES = [UserRoles.SUPER_ADMIN_ROLE, UserRoles.ADMIN_ROLE];

export const MANAGER_ROLES = [UserRoles.SUPER_ADMIN_ROLE, UserRoles.MANAGER_ROLE, UserRoles.ADMIN_ROLE];
